version: "3.7"

services:
  mock:
    image: stoplight/prism:3.2
    volumes:
      - "./dist:/app"
    command:
      - mock
      - "--host"
      - "0.0.0.0"
      - "/app/openapi.json"
    ports:
      - "4010:4010"

  swagger:
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
